### ISSUE TITLE
afas-cli generate > updateconnectors required?

### ISSUE THREAD

**Issue by imMarkdeVries** [dutchgrit/afascli#1]
Goodmorning,

Just tried your afas-cli for the first time. 
It will surely save me some time if this works

My assigned afas token has only get connectors.
I expected the C# classes for the results of these Get connectors to be generated .

Instead I get this error.

Regards,
Mark

unhandled exception. Newtonsoft.Json.JsonSerializationException: Required property 'updateConnectors' not found in JSON. Path '', line 4, position 127.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EndProcessProperty(Object newObject, JsonReader reader, JsonObjectContract contract, Int32 initialDepth, JsonProperty property, PropertyPresence presence, Boolean setDefaultValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at DutchGrit.Afas.BaseClient.GetApiAsync[T](String urlPath)
   at DutchGrit.Afas.GenerateCommand.<>c__DisplayClass1_0.<<AddGenerateCommand>b__2>d.MoveNext() in /home/runner/work/afascli/afascli/src/GenerateCommand.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplicationExtensions.<>c__DisplayClass8_0.<<OnExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at AfasClient.Cli.Program.Main(String[] args) in /home/runner/work/afascli/afascli/src/Program.cs:line 55

**Comment by LucasVos** [comment]
Dear Mark, 

Thank you for your feedback. 
And yes, you have discovered a bug! It is fixed in the new release.

You can update your current afas-cli with the following command:

`dotnet tool update afas-cli --global`

You should get a message: Tool 'afas-cli' was successfully updated from version '1.0.24' to version '1.0.31'.

**Comment by imMarkdeVries** [comment]
Dear Lucas,

Tested. 
Thank you for your fast response and sharing your Afas client.
Great work. Works like a charm.
Regards Mark
